import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main className="max-w-3xl px-6 mx-auto lg:max-w-6xl lg:px-8">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
